language: java

sudo: required

services:
  - docker

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode --show-version --settings .travis.settings.xml

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build . -t sshaddicts/neuralswarm;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push sshaddicts/neuralswarm;
    fi

cache:
  directories:
  - .autoconf
  - $HOME/.m2

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify