version: '2'

services:
  crossbar:
    build: ./crossbar
    ports:
      - "7778:7778"

  mongo:
    image: mongo
    logging:
      driver: none
    ports:
      - "27017:27017"

  neuralswarm:
    build: .
    depends_on:
      - crossbar
      - mongo