version: '2'

services:
  crossbar:
      build: ./.crossbar
      ports:
       - "7777:7777"
#  mongo:
#    image: mongo
#    restart: always
#    logging:
#      driver: none
#  neuralswarm:
#    build: .
#    logging:
#      driver: syslog