version: '2'

services:
  crossbar:
    image: sshaddicts/crossbar-for-neuralswarm:latest
    ports:
      - "7778:7778"

  mongo:
    image: mongo
    logging:
      driver: none
    ports:
      - "27017:27017"

  neuralswarm:
    image: neuralswarm:latest