version: '2'

services:
  crossbar:
    image: sshaddicts/crossbar-for-neuralswarm:latest
    ports:
      - "7778:7778"

  mongo:
    image: mongo
    logging:
      driver: none

  neuralswarm:
    build: .
    depends_on:
      - crossbar
      - mongo
  graylog:
    image: gophernet/netcat
    command: '-k -u -l -p 12201'
    logging:
      driver: none